import SessionProvider from "@/components/SessionProvider";
import { authOption } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import "../styles/globals.css";

export const metadata = {
  title: "Movie NIGHT",
  description: "Generated by create next app",
  icons:
    "../public/logo.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOption);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
